# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database job_parsing;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - ikioresko@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="05cd8bce-808c-4596-8a0f-49c36913c3d8"